version: '3'

services:
# node
  node:
    build: .
    volumes:
      - ./server.js:/src/server.js
      - ./data.js:/src/data.js
      - ./package.json:/src/package.json
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start"
